// Code generated by MockGen. DO NOT EDIT.
// Source: companyService.go
//
// Generated by this command:
//
//	mockgen -source=companyService.go -destination=companyservice_mock.go -package=services
//
// Package services is a generated GoMock package.
package services

import (
	model "project/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCompanyService is a mock of CompanyService interface.
type MockCompanyService struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyServiceMockRecorder
}

// MockCompanyServiceMockRecorder is the mock recorder for MockCompanyService.
type MockCompanyServiceMockRecorder struct {
	mock *MockCompanyService
}

// NewMockCompanyService creates a new mock instance.
func NewMockCompanyService(ctrl *gomock.Controller) *MockCompanyService {
	mock := &MockCompanyService{ctrl: ctrl}
	mock.recorder = &MockCompanyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyService) EXPECT() *MockCompanyServiceMockRecorder {
	return m.recorder
}

// CompanyCreate mocks base method.
func (m *MockCompanyService) CompanyCreate(nc model.CreateCompany) (model.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompanyCreate", nc)
	ret0, _ := ret[0].(model.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompanyCreate indicates an expected call of CompanyCreate.
func (mr *MockCompanyServiceMockRecorder) CompanyCreate(nc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompanyCreate", reflect.TypeOf((*MockCompanyService)(nil).CompanyCreate), nc)
}

// GetAllCompanies mocks base method.
func (m *MockCompanyService) GetAllCompanies() ([]model.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCompanies")
	ret0, _ := ret[0].([]model.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCompanies indicates an expected call of GetAllCompanies.
func (mr *MockCompanyServiceMockRecorder) GetAllCompanies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCompanies", reflect.TypeOf((*MockCompanyService)(nil).GetAllCompanies))
}

// GetAllJobs mocks base method.
func (m *MockCompanyService) GetAllJobs() ([]model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllJobs")
	ret0, _ := ret[0].([]model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllJobs indicates an expected call of GetAllJobs.
func (mr *MockCompanyServiceMockRecorder) GetAllJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllJobs", reflect.TypeOf((*MockCompanyService)(nil).GetAllJobs))
}

// GetCompanyById mocks base method.
func (m *MockCompanyService) GetCompanyById(id int) (model.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyById", id)
	ret0, _ := ret[0].(model.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyById indicates an expected call of GetCompanyById.
func (mr *MockCompanyServiceMockRecorder) GetCompanyById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyById", reflect.TypeOf((*MockCompanyService)(nil).GetCompanyById), id)
}

// GetJobByJobId mocks base method.
func (m *MockCompanyService) GetJobByJobId(id uint) (model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobByJobId", id)
	ret0, _ := ret[0].(model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobByJobId indicates an expected call of GetJobByJobId.
func (mr *MockCompanyServiceMockRecorder) GetJobByJobId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobByJobId", reflect.TypeOf((*MockCompanyService)(nil).GetJobByJobId), id)
}

// GetJobsByCompanyId mocks base method.
func (m *MockCompanyService) GetJobsByCompanyId(id int) ([]model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobsByCompanyId", id)
	ret0, _ := ret[0].([]model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobsByCompanyId indicates an expected call of GetJobsByCompanyId.
func (mr *MockCompanyServiceMockRecorder) GetJobsByCompanyId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobsByCompanyId", reflect.TypeOf((*MockCompanyService)(nil).GetJobsByCompanyId), id)
}

// JobCreate mocks base method.
func (m *MockCompanyService) JobCreate(nj model.CreateJob, id uint64) (model.JobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobCreate", nj, id)
	ret0, _ := ret[0].(model.JobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobCreate indicates an expected call of JobCreate.
func (mr *MockCompanyServiceMockRecorder) JobCreate(nj, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobCreate", reflect.TypeOf((*MockCompanyService)(nil).JobCreate), nj, id)
}

// ProcessingJobDetails mocks base method.
func (m *MockCompanyService) ProcessingJobDetails(arg0 []model.JobRequest) ([]model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessingJobDetails", arg0)
	ret0, _ := ret[0].([]model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessingJobDetails indicates an expected call of ProcessingJobDetails.
func (mr *MockCompanyServiceMockRecorder) ProcessingJobDetails(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessingJobDetails", reflect.TypeOf((*MockCompanyService)(nil).ProcessingJobDetails), arg0)
}
