// Code generated by MockGen. DO NOT EDIT.
// Source: jobDao.go
//
// Generated by this command:
//
//	mockgen -source=jobDao.go -destination=companyrepository_mock.go -package=repository
//
// Package repository is a generated GoMock package.
package repository

import (
	model "project/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCompany is a mock of Company interface.
type MockCompany struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyMockRecorder
}

// MockCompanyMockRecorder is the mock recorder for MockCompany.
type MockCompanyMockRecorder struct {
	mock *MockCompany
}

// NewMockCompany creates a new mock instance.
func NewMockCompany(ctrl *gomock.Controller) *MockCompany {
	mock := &MockCompany{ctrl: ctrl}
	mock.recorder = &MockCompanyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompany) EXPECT() *MockCompanyMockRecorder {
	return m.recorder
}

// CreateCompany mocks base method.
func (m *MockCompany) CreateCompany(arg0 model.Company) (model.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompany", arg0)
	ret0, _ := ret[0].(model.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompany indicates an expected call of CreateCompany.
func (mr *MockCompanyMockRecorder) CreateCompany(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompany", reflect.TypeOf((*MockCompany)(nil).CreateCompany), arg0)
}

// CreateJob mocks base method.
func (m *MockCompany) CreateJob(j model.Job) (model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", j)
	ret0, _ := ret[0].(model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockCompanyMockRecorder) CreateJob(j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockCompany)(nil).CreateJob), j)
}

// GetAllCompany mocks base method.
func (m *MockCompany) GetAllCompany() ([]model.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCompany")
	ret0, _ := ret[0].([]model.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCompany indicates an expected call of GetAllCompany.
func (mr *MockCompanyMockRecorder) GetAllCompany() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCompany", reflect.TypeOf((*MockCompany)(nil).GetAllCompany))
}

// GetAllJobs mocks base method.
func (m *MockCompany) GetAllJobs() ([]model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllJobs")
	ret0, _ := ret[0].([]model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllJobs indicates an expected call of GetAllJobs.
func (mr *MockCompanyMockRecorder) GetAllJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllJobs", reflect.TypeOf((*MockCompany)(nil).GetAllJobs))
}

// GetCompany mocks base method.
func (m *MockCompany) GetCompany(id int) (model.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompany", id)
	ret0, _ := ret[0].(model.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompany indicates an expected call of GetCompany.
func (mr *MockCompanyMockRecorder) GetCompany(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompany", reflect.TypeOf((*MockCompany)(nil).GetCompany), id)
}

// GetJobTypeById mocks base method.
func (m *MockCompany) GetJobTypeById(id uint) (model.JobType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobTypeById", id)
	ret0, _ := ret[0].(model.JobType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobTypeById indicates an expected call of GetJobTypeById.
func (mr *MockCompanyMockRecorder) GetJobTypeById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobTypeById", reflect.TypeOf((*MockCompany)(nil).GetJobTypeById), id)
}

// GetJobs mocks base method.
func (m *MockCompany) GetJobs(id int) ([]model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobs", id)
	ret0, _ := ret[0].([]model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobs indicates an expected call of GetJobs.
func (mr *MockCompanyMockRecorder) GetJobs(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobs", reflect.TypeOf((*MockCompany)(nil).GetJobs), id)
}

// GetJobsByJobId mocks base method.
func (m *MockCompany) GetJobsByJobId(id uint) (model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobsByJobId", id)
	ret0, _ := ret[0].(model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobsByJobId indicates an expected call of GetJobsByJobId.
func (mr *MockCompanyMockRecorder) GetJobsByJobId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobsByJobId", reflect.TypeOf((*MockCompany)(nil).GetJobsByJobId), id)
}

// GetLocationById mocks base method.
func (m *MockCompany) GetLocationById(id uint) (model.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocationById", id)
	ret0, _ := ret[0].(model.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocationById indicates an expected call of GetLocationById.
func (mr *MockCompanyMockRecorder) GetLocationById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocationById", reflect.TypeOf((*MockCompany)(nil).GetLocationById), id)
}

// GetQualificationById mocks base method.
func (m *MockCompany) GetQualificationById(id uint) (model.Qualification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQualificationById", id)
	ret0, _ := ret[0].(model.Qualification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQualificationById indicates an expected call of GetQualificationById.
func (mr *MockCompanyMockRecorder) GetQualificationById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQualificationById", reflect.TypeOf((*MockCompany)(nil).GetQualificationById), id)
}

// GetShiftById mocks base method.
func (m *MockCompany) GetShiftById(id uint) (model.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftById", id)
	ret0, _ := ret[0].(model.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShiftById indicates an expected call of GetShiftById.
func (mr *MockCompanyMockRecorder) GetShiftById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftById", reflect.TypeOf((*MockCompany)(nil).GetShiftById), id)
}

// GetTechnologyById mocks base method.
func (m *MockCompany) GetTechnologyById(id uint) (model.Technology, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTechnologyById", id)
	ret0, _ := ret[0].(model.Technology)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTechnologyById indicates an expected call of GetTechnologyById.
func (mr *MockCompanyMockRecorder) GetTechnologyById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTechnologyById", reflect.TypeOf((*MockCompany)(nil).GetTechnologyById), id)
}
